### PR TITLE
add performance report to GUI

### PR DESCRIPTION
**Pull request by ssalniyat**
but there is an relative path issue, so i uses the absolute path

### CODE REVIEW

**Comment by ssalniyat** [comment]
I just messed in the commit branchs..

**Comment by sotchatzi** [comment]
The relative path like this one:
new System.IO.StreamWriter(@"reportTime.txt", true))
Does not work?

**Comment by ssalniyat** [comment]
It saves under the ProformanceTests\ directory, but we are running our GUI at WpfApp\

**Comment by ssalniyat** [comment]
I have already made the relative path work now

**Comment by sotchatzi** [comment]
If I am not mistaken you are still using the same absolute path
string textFile = @"C:\Users\DELL\source\repos\sotchatzi\Big-Data-in-GUI\PerformanceTests\bin\Debug\netcoreapp3.1\reportTime.txt";

fs = new FileStream(textFile, FileMode.Open, FileAccess.Read);

**Comment by ssalniyat** [comment]
wow thank you!!! It is a typo, I changed the .exit but forget to change the FileStream

**Pull request merged**
